spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kotlindemo?useSSL=false&serverTimezone=UTC
    username: myuser
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
